### ISSUE TITLE
Current state and future state of the package

### ISSUE THREAD

**Issue by Midnighter** [supermihi/gurobimh#3]
Hi there, we use the official Python bindings for our project biosustain/optlang but I'm not super happy with how to set up Gurobi (in particular having to mess with `LD_LIBRARY_PATH`) and I'd prefer self compiled bindings.

What is the current state of the project though? Are you still maintaining it and simply nothing has come up over the last two years? Is it abandoned? What are your plans for the future?

**Comment by supermihi** [comment]
Hi. This package is practically orphaned, as I don't use the Gurobi/Python interface currently. I'd be happy to see this continuing, but so far no maintainer has shown up.

By the way, this package does not save you from "messing" with `LD_LIBRARY_PATH`, because the python library still needs to find the official `gurobi` shared library to operate!

**Comment by Midnighter** [comment]
> Hi. This package is practically orphaned, as I don't use the Gurobi/Python interface currently. I'd be happy to see this continuing, but so far no maintainer has shown up.

Alright, thank you for letting me know.

> By the way, this package does not save you from "messing" with `LD_LIBRARY_PATH`, because the python library still needs to find the official gurobi shared library to operate!

Well, my hope was that with something I compile myself I could use `-Wl,-rpath` as a compile time argument thus avoiding messing with `LD_LIBRARY_PATH`.
